Repository bounswe/2021SpringGroup4, pull requests merged in 2021-06, with the labels that each got.

#62 Practice-app: Register API
  practice-app/api/register/__init__.py
  practice-app/api/register/__pycache__/__init__.cpython-38.pyc
  practice-app/api/register/__pycache__/__init__.cpython-39.pyc
  practice-app/api/register/__pycache__/forms.cpython-38.pyc
  practice-app/api/register/__pycache__/forms.cpython-39.pyc
  practice-app/api/register/__pycache__/register.cpython-38.pyc
  practice-app/api/register/__pycache__/register.cpython-39.pyc
  practice-app/api/register/__pycache__/test_register.cpython-38.pyc
  practice-app/api/register/forms.py
  practice-app/api/register/register.py
  practice-app/api/register/test_register.py
Labels: Status: Review Needed, Type: Development

#64 Practice-app: Places API
  practice-app/api/places/__pycache__/forms.cpython-38.pyc
  practice-app/api/places/__pycache__/forms.cpython-39.pyc
  practice-app/api/places/__pycache__/places.cpython-38.pyc
  practice-app/api/places/__pycache__/places.cpython-39.pyc
  practice-app/api/places/forms.py
  practice-app/api/places/places.py
  practice-app/api/places/test_places.py
Labels: Backend, Type: Development

#69 Practice-app: Covid19 API
  images/project plan/1.png
  images/project plan/10.png
  images/project plan/11.png
  images/project plan/12.png
  images/project plan/2.png
  images/project plan/3.png
  images/project plan/4.png
  images/project plan/5.png
  images/project plan/6.png
  images/project plan/7.png
  images/project plan/8.png
  images/project plan/9.png
  practice-app/.idea/inspectionProfiles/Project_Default.xml
  practice-app/.idea/workspace.xml
  practice-app/api/__pycache__/views.cpython-39.pyc
  practice-app/api/covid_reports/__pycache__/main.cpython-39.pyc
  practice-app/api/covid_reports/main.py
  practice-app/api/covid_reports/test_covid.py
  practice-app/api/views.py
Labels: Discussion Request, enhancement

#67 Practice-app: Formula 1 API
  practice-app/api/formula1/__pycache__/formula1.cpython-39.pyc
  practice-app/api/formula1/formula1.py
  practice-app/api/formula1/test_formula1.py
  practice-app/api/urls.py
  practice-app/api/views.py
  practice-app/templates/driver_information.html
  practice-app/templates/formula1_standings.html
Labels: Backend, Frontend, Status: Review Needed

#76 Berkaygumus
  practice-app/api/teams/__pycache__/choice_level.cpython-37.pyc
  practice-app/api/teams/__pycache__/choice_team.cpython-37.pyc
  practice-app/api/teams/__pycache__/choice_tutorial.cpython-37.pyc
  practice-app/api/teams/__pycache__/main.cpython-37.pyc
  practice-app/api/teams/choice_team.py
  practice-app/api/teams/main.py
  practice-app/api/urls.py
  practice-app/api/views.py
  practice-app/requirements.txt
  practice-app/templates/list_team.html
  practice-app/templates/team.html
Labels: Status: Review Needed

#70 Holidays api
  practice-app/api/__pycache__/tests.cpython-39.pyc
  practice-app/api/covid_reports/__pycache__/test_covid.cpython-39.pyc
  practice-app/api/eq_post/__pycache__/test_eq_post.cpython-39.pyc
  practice-app/api/holidays/__init__.py
  practice-app/api/holidays/__pycache__/__init__.cpython-39.pyc
  practice-app/api/holidays/__pycache__/holiday_form.cpython-39.pyc
  practice-app/api/holidays/__pycache__/main.cpython-39.pyc
  practice-app/api/holidays/__pycache__/test_holidays.cpython-39.pyc
  practice-app/api/holidays/holiday_form.py
  practice-app/api/holidays/main.py
  practice-app/api/holidays/test_holidays.py
  practice-app/api/random_article/__pycache__/test_ra.cpython-39.pyc
  practice-app/api/register/__pycache__/test_register.cpython-39.pyc
  practice-app/api/urls.py
  practice-app/api/views.py
  practice-app/templates/holidays.html
Labels: Status: Review Needed
