Repository bounswe/2021SpringGroup4, pull requests merged in 2022-01, with the labels that each got.

#215 Equipment API updates and related search functionality
  code/backend/activity_handler/migrations/0001_initial.py
  code/backend/activity_handler/migrations/0002_auto_20211130_1308.py
  code/backend/api/authentication/migrations/0001_initial.py
  code/backend/api/authentication/migrations/0002_user_profile_picture.py
  code/backend/api/badges/migrations/0001_initial.py
  code/backend/api/equipment/migrations/0001_initial.py
  code/backend/api/equipment/models.py
  code/backend/api/equipment/serializers.py
  code/backend/api/events/migrations/0001_initial.py
  code/backend/api/events/migrations/0002_auto_20211127_1539.py
  code/backend/api/events/migrations/0003_alter_comment_parent.py
  code/backend/api/events/migrations/0004_alter_comment_parent.py
  code/backend/api/events/migrations/0005_auto_20211210_1814.py
  code/backend/api/search/migrations/__init__.py
  code/backend/api/search/urls.py
  code/backend/api/search/views.py
Labels: Backend

#226 Android dev ece
  app/build.gradle
  app/src/main/java/com/example/sportshub/profile/BadgeAdapter.kt
  app/src/main/java/com/example/sportshub/profile/GetEventDetailListener.kt
  app/src/main/java/com/example/sportshub/profile/GetProfileListener.kt
  app/src/main/java/com/example/sportshub/profile/GrantBadgeListener.kt
  app/src/main/java/com/example/sportshub/profile/ProfileEventAdapter.kt
  app/src/main/java/com/example/sportshub/profile/ProfileFragment.kt
  app/src/main/java/com/example/sportshub/profile/ProfileViewModel.kt
  app/src/main/java/com/example/sportshub/profile/model/BadgeModel.kt
  app/src/main/java/com/example/sportshub/profile/model/ProfileModel.kt
  app/src/main/res/drawable-anydpi/ic_action_name.xml
  app/src/main/res/drawable-hdpi/ic_action_name.png
  app/src/main/res/drawable-hdpi/ic_crybaby.png
  app/src/main/res/drawable-hdpi/ic_friendly.png
  app/src/main/res/drawable-hdpi/ic_gentleman.png
  app/src/main/res/drawable-hdpi/ic_master.png
  app/src/main/res/drawable-hdpi/ic_novice.png
  app/src/main/res/drawable-hdpi/ic_skilled.png
  app/src/main/res/drawable-hdpi/ic_sore_loser.png
  app/src/main/res/drawable-hdpi/ic_top_organizer.png
  app/src/main/res/drawable-mdpi/ic_action_name.png
  app/src/main/res/drawable-mdpi/ic_crybaby.png
  app/src/main/res/drawable-mdpi/ic_friendly.png
  app/src/main/res/drawable-mdpi/ic_gentleman.png
  app/src/main/res/drawable-mdpi/ic_master.png
  app/src/main/res/drawable-mdpi/ic_novice.png
  app/src/main/res/drawable-mdpi/ic_skilled.png
  app/src/main/res/drawable-mdpi/ic_sore_loser.png
  app/src/main/res/drawable-mdpi/ic_top_organizer.png
  app/src/main/res/drawable-xhdpi/ic_action_name.png
  app/src/main/res/drawable-xhdpi/ic_crybaby.png
  app/src/main/res/drawable-xhdpi/ic_friendly.png
  app/src/main/res/drawable-xhdpi/ic_gentleman.png
  app/src/main/res/drawable-xhdpi/ic_master.png
  app/src/main/res/drawable-xhdpi/ic_novice.png
  app/src/main/res/drawable-xhdpi/ic_skilled.png
  app/src/main/res/drawable-xhdpi/ic_sore_loser.png
  app/src/main/res/drawable-xhdpi/ic_top_organizer.png
  app/src/main/res/drawable-xxhdpi/ic_action_name.png
  app/src/main/res/drawable-xxhdpi/ic_crybaby.png
  app/src/main/res/drawable-xxhdpi/ic_friendly.png
  app/src/main/res/drawable-xxhdpi/ic_gentleman.png
  app/src/main/res/drawable-xxhdpi/ic_master.png
  app/src/main/res/drawable-xxhdpi/ic_novice.png
  app/src/main/res/drawable-xxhdpi/ic_skilled.png
  app/src/main/res/drawable-xxhdpi/ic_sore_loser.png
  app/src/main/res/drawable-xxhdpi/ic_top_organizer.png
  app/src/main/res/drawable-xxxhdpi/ic_crybaby.png
  app/src/main/res/drawable-xxxhdpi/ic_friendly.png
  app/src/main/res/drawable-xxxhdpi/ic_gentleman.png
  app/src/main/res/drawable-xxxhdpi/ic_master.png
  app/src/main/res/drawable-xxxhdpi/ic_novice.png
  app/src/main/res/drawable-xxxhdpi/ic_skilled.png
  app/src/main/res/drawable-xxxhdpi/ic_sore_loser.png
  app/src/main/res/drawable-xxxhdpi/ic_top_organizer.png
  app/src/main/res/layout/badge_item.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/profile_event_item.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: Priority: High, Type: Development, Android

#231 Android dev ece
  app/src/main/java/com/example/sportshub/event/CreateEventMapFragment.kt
  app/src/main/java/com/example/sportshub/event/EventCreateFragment.kt
  app/src/main/java/com/example/sportshub/event/EventDetailFragment.kt
  app/src/main/java/com/example/sportshub/event/EventUpdateFragment.kt
  app/src/main/java/com/example/sportshub/event/EventViewModel.kt
  app/src/main/java/com/example/sportshub/event/SharedViewModelCreateEvent.kt
  app/src/main/java/com/example/sportshub/event/SharedViewModelUpdateEvent.kt
  app/src/main/java/com/example/sportshub/profile/ProfileFragment.kt
  app/src/main/res/drawable-hdpi/ic_logout.png
  app/src/main/res/drawable-mdpi/ic_logout.png
  app/src/main/res/drawable-xhdpi/ic_logout.png
  app/src/main/res/drawable-xxhdpi/ic_logout.png
  app/src/main/res/drawable-xxxhdpi/ic_logout.png
  app/src/main/res/layout/event_detail_fragment.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: Priority: Critical, Android
